name: Deploy Project

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        container:
            image: node:23
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build